@startuml APIUseCaseDiagram
title Api UseCase Diagram

actor Client

usecase SignIn
usecase SignUp
usecase GeneratePassword
usecase ManipulatePassword
usecase ValidateHash

Client -- SignIn
Client -- SignUp
Client -- GeneratePassword
Client -- ManipulatePassword
Client -- ValidateHash

@enduml